# Generated by Django 2.1 on 2019-01-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='washer',
            name='master_phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
