# Generated by Django 2.1 on 2019-02-06 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_washer_master_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('sms_code', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('-createAt',),
            },
        ),
    ]
