# Generated by Django 2.1 on 2019-02-06 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_verifycode_expire_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifycode',
            old_name='phone_number',
            new_name='tel_phone',
        ),
        migrations.RenameField(
            model_name='verifycode',
            old_name='sms_code',
            new_name='verify_code',
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='expire_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
