# Generated by Django 2.1 on 2019-02-06 23:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20190206_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayedLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('api_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=30)),
                ('trade_no', models.CharField(max_length=50)),
                ('sign', models.CharField(max_length=500)),
                ('out_trade_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Order')),
            ],
            options={
                'ordering': ('-createAt',),
            },
        ),
    ]
