# Generated by Django 2.1 on 2019-02-07 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_orderpayedlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsocketChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('channel_name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Washer')),
            ],
            options={
                'ordering': ('-createAt',),
            },
        ),
    ]
