# Generated by Django 2.1 on 2019-02-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_websocketchannel_disconnect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websocketchannel',
            old_name='disconnect',
            new_name='is_group',
        ),
    ]
