# Generated by Django 2.1 on 2019-02-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_websocketchannel_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websocketchannel',
            name='group_name',
            field=models.CharField(choices=[('group_name_choices', 'channel_group_order')], default='', max_length=20),
        ),
    ]
