# Generated by Django 2.1 on 2019-02-07 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20190207_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting_pay', 'WAITING_PAY'), ('order_payed', 'ORDER_PAYED'), ('waiting_washing', 'WAITING_WASHING'), ('order_timeout', 'ORDER_TIMEOUT'), ('order_finish', 'ORDER_FINISH'), ('order_cancel', 'ORDER_CANCEL'), ('order_refund', 'ORDER_REFUND')], default='WAITING_PAY', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='washer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Washer'),
        ),
    ]
